#!/bin/bash
### BEGIN INIT INFO
# Description: Runs clippy pedantic and then the program
### END INIT INFO

# Author: Robin Chapple <r.chapple.business@gmail.com>

cargo clippy -- -W clippy::pedantic
cargo run $1
